### ISSUE TITLE
the decider

### ISSUE THREAD

**Issue by ninjabear** [10xers/2015#22]
what we doin

**Comment by MatthewJWalls** [comment]
We should narrow everything down to a shortlist I guess.

**Comment by MatthewJWalls** [comment]
I'm going to create a new label called proposed-veto. I'll add it to my tickets if I think they definitely shouldn't be on the shortlist.

**Comment by ninjabear** [comment]
I've added proposed-veto to mine. I think we should weed out our own ideas first before we start the bumfight over whos idea to pick

![bumfight.jpg](http://matchbin-assets.s3.amazonaws.com/public/sites/351/assets/7H7E_Rufus_Before.jpg)
