### ISSUE TITLE
speed reader

### ISSUE THREAD

**Issue by ninjabear** [10xers/2015#9]
I really like this tool [spritz](http://www.spritzinc.com/) and I'm pretty amazed that I can read at like 700wpm without much effort. It could do with a few tweaks though like slowing down on unusual words, and the UX is horribad.

A speed reader like this would be good, not sure about IP rules. 

This would also be pretty epic if it could be applied to code. Some kind of englishifier ?

**Comment by MatthewJWalls** [comment]
Digression: I wish I could annotate source control repos. Add custom views, bookmarks, favorites, write notes, etc.

**Comment by ninjabear** [comment]
yeah. 

Thinking about it if could get the blurb from all my RSS feeds through this I could be done in about a minute. Same with emails.

https://www.youtube.com/watch?v=SRs8DgV1cDE

**Comment by ninjabear** [comment]
Also, usefully because its a WPM style thing, it gives you an exact amount of time it would take to read your emails down to the second

**Comment by ninjabear** [comment]
https://github.com/ninjabear/SpeedReadExample

**Comment by ninjabear** [comment]
NB. some optimisation necessary. Like slowing down for punctuation and infrequently used words

**Comment by ninjabear** [comment]
I hadn't actually specifically mentioned that the way i propose we get around the UX of the online tools is to hook it up to a users emails.

It would replace their email client for reading email. 

So for example, you open the application and it says ... read 20 new emails? Estimated time 20 seconds, if you hit "Go" it speed reads each in succession, or with a pause between emails. You could then press "UP" or another button to open it in detail, "RIGHT" to skip to next, "LEFT" previous and so on. 

It would require some work neatening up the algorithm, but the IMAP/POP3 libs already exist. It would also be nice to have a mobile edition of this as its just as easy to read one word at a time on a mobile device as it is on a desktop screen.

**Comment by ninjabear** [comment]
doing some reading... dat academic paywall. swartz rip

**Comment by ninjabear** [comment]
ill write up some better docs later but basically this kind of tech has been around for a long time. The problem is always the UX. It's either clunky, reads the wrong text or is designed for the wrong kind of thing. You wouldn't want to speed read a very complicated scientific paper etc, it just takes a long time and lots of rereading passages for them to sink in.

Comprehension of emails though - most people only skim them anyway. If we could make the UX amaze I think that's gotta be the main effort.

Some cursory extra notes from me; the size of the text is an important variable, i thought it'd be easier with larger text but this isn't the case. The spritz style bar thing also isn't required (as my demo proved). Flickering on the screen is also very annoying, and you do notice it, i guess the framerate is quite low for most text renderers.

**Comment by MatthewJWalls** [comment]
Super annoying that I can't spritz a pdf or anything from my browser. I'm not that interested in speed reading internet articles because they're high in unparseable cruft like headings and titles, and so short that it's not worth the mental overhead of loading spritz up. PDFs and books though you'd think would be obvious candidates; who wouldn't want to finish a book in an afternoon? But spritz just doesn't support that at all. The mobile versions might, but I'm not going to pay for an app that's basically a while loop, a weighted sleep, and a textbox.

**Comment by ninjabear** [comment]
Yeah, the current tools haven't really considered that not everything is speed-readable. Why would I want to speed read my grans will or something. There's a time an a place. I think that place is probably email - well at least its the most obvious candidate.

Books are an interesting one, I would like to read a book in an afternoon, but comprehension is really important. I wouldn't want to miss a sentence because it might alter the narrative (e.g. murder mystery - what if I miss a clue?). We'd need a lot of "replay sentence" etc style buttons. 

As for the algo itself, it is largely a while loop. The "Optimal recognition point" (ORP) as spritz calls it (the red letter) does seem to be helpful, however I think there are more obvious alterations to the algorithm would be better.

For example - It takes me a fraction of the time to read "the", "and", "at" etc as it does to read "autotonsorialist". Unusual words need to stay up for longer, not because it takes me longer to eye them but because something more is going on upstairs trying to work out what that word is.

**Comment by ninjabear** [comment]
![image](https://cloud.githubusercontent.com/assets/5323141/5994033/48491598-aa5d-11e4-9a89-4759212854cb.png)
